### PR TITLE
PRO-18:Uploading uploadPropImages

### PR DESCRIPTION
**Pull request by GulzatB**

### CODE REVIEW

**Comment by belekomurzakov** [comment]
@GulzatB, what this? :)

**Comment by GulzatB** [comment]
> 

To upload property Images.

**Review by belekomurzakov — APPROVED** [review]

**Comment by belekomurzakov** [comment]
Screenshot 2022-07-25 at 17 22 25
don't forget to click on this button

**Comment by GulzatB** [comment]
Had merged.

**Pull request merged**
